#!/bin/sh
/opt/qemu/bin/qemu-system-x86_64 \
	-display none \
	-vga none \
	-serial mon:stdio \
	-nodefaults \
	-m 512 \
	-machine pc \
	-kernel ./kernel.small \
	-machine type=pc-i440fx-3.1 \
	-no-user-config \
	-pidfile fail-os.pid \
	-net nic,model=pcnet \
	-hda disk.raw \
	$*

exit 0

	#-accel kvm \
	#-cpu host \
	-runas $(whoami) \
